# Generated by Django 4.2.11 on 2024-04-17 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_timestamp', models.DateTimeField(default=datetime.datetime(2024, 4, 17, 9, 32, 51, 481443, tzinfo=datetime.timezone.utc))),
                ('devId', models.CharField(max_length=50)),
                ('corr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CorrelationToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_timestamp', models.DateTimeField(default=datetime.datetime(2024, 4, 17, 9, 32, 51, 481443, tzinfo=datetime.timezone.utc))),
                ('devId', models.CharField(max_length=50)),
                ('corr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.date(2024, 4, 17))),
                ('power', models.FloatField()),
            ],
        ),
    ]
