# Generated by Django 4.2.11 on 2024-04-17 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlationmonth',
            name='calculation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 9, 45, 4, 927589, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='correlationtoday',
            name='calculation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 9, 45, 4, 927589, tzinfo=datetime.timezone.utc)),
        ),
    ]
