# Generated by Django 4.2.11 on 2024-06-13 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0002_alter_correlationmonth_calculation_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='correlationmonth',
            name='calculation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 14, 52, 4, 557233, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='correlationtoday',
            name='calculation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 14, 52, 4, 556594, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date(2024, 6, 13)),
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_value', models.FloatField()),
                ('feature1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature1', to='mlapp.feature')),
                ('feature2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature2', to='mlapp.feature')),
            ],
            options={
                'ordering': ['feature1', 'feature2'],
                'unique_together': {('feature1', 'feature2')},
            },
        ),
    ]
