# Generated by Django 4.2.11 on 2024-06-14 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0003_feature_alter_correlationmonth_calculation_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlation',
            name='devId',
            field=models.CharField(default='devId', max_length=50),
        ),
        migrations.AlterField(
            model_name='correlationmonth',
            name='calculation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 13, 10, 48, 791119, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='correlationtoday',
            name='calculation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 13, 10, 48, 791119, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date(2024, 6, 14)),
        ),
    ]
