# Generated by Django 4.2.11 on 2024-06-17 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0004_correlation_devid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlation',
            name='period',
            field=models.CharField(default='today', max_length=50),
        ),
        migrations.AlterField(
            model_name='correlationmonth',
            name='calculation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 7, 9, 45, 192189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='correlationtoday',
            name='calculation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 7, 9, 45, 191157, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date(2024, 6, 17)),
        ),
    ]
