# Generated by Django 4.2.11 on 2024-06-17 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0005_correlation_period_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='correlation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='correlationmonth',
            name='calculation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 13, 44, 17, 887625, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='correlationtoday',
            name='calculation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 13, 44, 17, 887625, tzinfo=datetime.timezone.utc)),
        ),
    ]
