# Generated by Django 4.2.11 on 2024-06-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0007_forecast_devid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorrelationMonth',
        ),
        migrations.DeleteModel(
            name='CorrelationToday',
        ),
    ]
