# Generated by Django 4.2.11 on 2024-11-07 15:21

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0008_delete_correlationmonth_delete_correlationtoday'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='forecast',
            managers=[
                ('resample', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='forecast',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date(2024, 11, 7)),
        ),
    ]
