# Generated by Django 4.2.19 on 2025-02-07 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0009_alter_forecast_managers_alter_forecast_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ppe', models.CharField(max_length=50)),
                ('farm', models.CharField(max_length=50)),
                ('production_forecast', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='forecast',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date(2025, 2, 7)),
        ),
    ]
